# 财报分析 / 结构分析 / 负债结构

name = "nonfin-structure-liability"
alias = "负债结构"
names = ["负债结构分析", "结构分析-负债结构", "liability_structure", "liability_structure#负债结构", "nonfin-structure-liability"]
type = "bar"
mode = "structure"

title = "负债结构分析"
x_label = "科目"
y_label = "金额"


[[series]]
name = "流动负债"
color = "#E15759"

  [[series.children]]
  name = "短期借款"
  expr = "bs.short_term_borrowings"

  [[series.children]]
  name = "应付票据"
  expr = "bs.notes_payable"

  [[series.children]]
  name = "应付账款"
  expr = "bs.accounts_payable"

  [[series.children]]
  name = "合同负债"
  expr = "bs.contract_liabilities"

  [[series.children]]
  name = "应付职工薪酬"
  expr = "bs.payroll_payable"

  [[series.children]]
  name = "应交税费"
  expr = "bs.taxes_payable"

  [[series.children]]
  name = "其他应付款"
  expr = "bs.other_payables"

  [[series.children]]
  name = "一年内到期的非流动负债"
  expr = "bs.ncl_due_within_one_year"

  [[series.children]]
  name = "流动负债合计"
  expr = "bs.total_current_liabilities"

[[series]]
name = "非流动负债"
color = "#F28E2B"

  [[series.children]]
  name = "长期借款"
  expr = "bs.long_term_borrowings"

  [[series.children]]
  name = "应付债券"
  expr = "bs.bonds_payable"

  [[series.children]]
  name = "预计负债"
  expr = "bs.provisions"

  [[series.children]]
  name = "递延收益"
  expr = "bs.deferred_income"

  [[series.children]]
  name = "递延所得税负债"
  expr = "bs.deferred_tax_liabilities"

  [[series.children]]
  name = "非流动负债合计"
  expr = "bs.total_non_current_liabilities"

  [[series.children]]
  name = "负债合计"
  expr = "bs.total_liabilities"
