# 归母净利润（单季）趋势

name = "nonfin-trend-net_profit_q"
alias = "归母净利润"

names = ["net_profit_q", "net_profit_q#净利润", "nonfin-trend-net_profit_q"]
type = "bar"

title = "归母净利润（单季）趋势"

x_label = "报告期"
y_label = "金额"

mode = "trend"

[[series]]
name = "归母净利润"
expr = "is.net_profit_parent - is.net_profit_parent.prev_in_year"
